//*****************************************************************************
//*****************************************************************************
//  FILENAME:  E2PROM.h
//  Version: 1.7, Updated on 2015/3/4 at 22:26:11
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION:
//    E2PROM Module header file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef E2PROM_INCLUDE
#define E2PROM_INCLUDE

/* include the global header file */
#include <m8c.h>

/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  E2PROM_Start         // class 1
#pragma fastcall16  E2PROM_Stop          // class 2
#pragma fastcall16  E2PROM_bE2Write      // class 4
#pragma fastcall16  E2PROM_E2Read        // class 4 

//-------------------------------------------------
// Prototypes of the E2PROM API.
//-------------------------------------------------
extern void  E2PROM_Start(void);      
extern void  E2PROM_Stop(void);
extern CHAR  E2PROM_bE2Write(WORD wAddr, BYTE * pbData, WORD wByteCount, CHAR cTemperature);
extern void  E2PROM_E2Read(WORD wAddr, BYTE * pbDataDest, WORD wByteCount);

//-------------------------------------------------
// Defines for E2PROM API's.
//-------------------------------------------------
/* Return value for bE2Write */
#define  E2PROM_NOERROR           0
#define  E2PROM_FAILURE          -1
#define  E2PROM_STACKOVERFLOW    -2

#define  E2PROM_START_BLOCK       0x7f                               // Starting block of E2PROM EEPROM device
#define  E2PROM_START_ADDR        (0x7f * 64)                        // absolute address of E2PROM EEPROM device
#define  E2PROM_LENGTH            0x40                               // length of E2PROM EEPROM device

#endif
// end of file E2PROM.h
